### PR TITLE
Fixes GH-916 by falling back to the old HTTP 413 Error Code if not present

### LINKED ISSUE #916: Restify test fails on Node 4
https://travis-ci.org/restify/node-restify/jobs/79522234

```
✖ GH-149 limit request body size
AssertionError: 500 == 413
    at Object.equal (/home/travis/build/restify/node-restify/node_modules/nodeunit/lib/types.js:83:39)
    at ClientRequest.<anonymous> (/home/travis/build/restify/node-restify/test/server.test.js:804:11)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

✖ GH-149 limit request body size (json)
AssertionError: 500 == 413
    at Object.equal (/home/travis/build/restify/node-restify/node_modules/nodeunit/lib/types.js:83:39)
    at ClientRequest.<anonymous> (/home/travis/build/restify/node-restify/test/server.test.js:834:11)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

### PR DESCRIPTION
**Pull request by micahr**
Add compatibility with Node 4 for Http Status Codes

Moving between Node 0.12 and 4 introduces different http status code
messages for the request body size is too large error (413). This should
normalize between the two, picking the one that is not undefined.

Fixes #916

### CODE REVIEW

**Comment by micahr** [comment]
I'd like to get this out as 4.0.3, so no one else has issues with receiving a 500 instead of a 413.

File: lib/plugins/body_reader.js [hunk 1]
```diff
@@ -86,12 +87,23 @@ function bodyReader(options) {
...
 
             if (maxBodySize && bytesReceived > maxBodySize) {
                 var msg = 'Request body size exceeds ' +
                     maxBodySize;
-                next(new RequestEntityTooLargeError(msg));
+
+                // Between Node 0.12 and 4 http status code messages changed
+                // RequestEntityTooLarge was changed to PayloadTooLarge
+                // this check is to maintain backwards compatibility
+                if (PayloadTooLargeError !== undefined) {
```
Comment (yunong) [inline lib/plugins/body_reader.js]: Great work, consider using `process.version` to switch on these error codes.

Comment (micahr) [inline lib/plugins/body_reader.js]: I knew there had to be a way to look that up.

Now that I have this in here, I think it might be less brittle to use the Error names, since it actually changed in iojs 3. And if someone is using Restify with iojs 3, we should not break that.

**Comment by yunong** [comment]
@micahr looks good, feel free to merge. Thanks for the quick fix.
