### PR TITLE
GH-1123: add deprecation warnings for domain dependent features

### LINKED ISSUE #1123: Add deprecation warnings for features requiring domains
Using the `handleUncaughtExceptions` flag will now trigger deprecation warnings. 

This also disables `next.ifError`, and only attaches the function if the flag is true since it requires domains.

### PR DESCRIPTION
**Pull request by DonutEspresso**
Fixes #1123

### CODE REVIEW

File: lib/server.js [hunk 1]
```diff
@@ -32,9 +31,8 @@ require('./response');
 ///--- Globals
 
 var sprintf = util.format;
-
+var maxSatisfying = semver.maxSatisfying;
```
Comment (micahr) [inline lib/server.js]: maximum satisfaction

**Comment by micahr** [comment]
LGTM

It may become necessary at some point to have a more centralized feature detection within Restify, especially if we are trying to support back to at least Node 0.12. Because the number of instances of checking `this.handleUncaughtExceptions` is pretty low, it isn't necessary now, but as the velocity of Node releases increases and interfaces continue to change, we might want to revisit how we handle this detection.

**Comment by DonutEspresso** [comment]
Yup. Sounds reasonable to me.
